#!/usr/bin/env python3
"""
workplace/core/handoff_validator.py

Percipience Multi-Agent Handover & Schema Validation Engine (CAP-09, CAP-26)
Enforces JSON Schema Draft-07 compliance for inter-agent messages and
verifies cryptographic HandoffTokens to prevent bypassed gates and shadow handovers.
"""

import hmac
import hashlib
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Any, Tuple, List, Optional

PLATFORM_HANDOFF_SECRET = b"percipience_enclave_handoff_hmac_secret_2026"

AUTHORIZED_HANDOFF_ROUTES = {
    "wf_cross_module_delivery_01": {
        ("agent_architect", "agent_provider_developer"): "gate_arch_review",
        ("agent_architect", "agent_consumer_developer"): "gate_arch_review",
        ("agent_provider_developer", "agent_integration_verifier"): "gate_provider_review",
        ("agent_consumer_developer", "agent_integration_verifier"): "gate_consumer_review",
        ("agent_integration_verifier", "agent_living_doc_architect"): "gate_cross_module_compatibility",
        ("agent_living_doc_architect", "agent_pr_gatekeeper"): "gate_doc_drift_verification"
    },
    "wf_pr_gatekeeper": {
        ("agent_ast_optimizer", "agent_dependency_cve_sentinel"): "stage_1_ast_diff",
        ("agent_dependency_cve_sentinel", "agent_contract_compatibility_checker"): "stage_2_cve_audit",
        ("agent_contract_compatibility_checker", "agent_flaky_test_detector"): "stage_3_contract_check",
        ("agent_flaky_test_detector", "agent_doc_drift_synchronizer"): "stage_4_flaky_test_check",
        ("agent_doc_drift_synchronizer", "agent_living_doc_architect"): "stage_5_tdd_doc_drift",
        ("agent_living_doc_architect", "agent_merkle_signer"): "stage_6_living_docs",
        ("agent_merkle_signer", "agent_worm_egress"): "stage_7_merkle_sealing"
    }
}


class HandoffValidator:
    """Validates inter-agent handoff messages, routes, and cryptographic proof tokens."""

    @staticmethod
    def generate_token(from_agent: str, to_agent: str, workflow_id: str, stage: str, gate_id: str) -> str:
        """Generates a cryptographic HMAC-SHA256 HandoffToken for verified stage transition."""
        message = f"{workflow_id}:{stage}:{gate_id}:{from_agent}->{to_agent}".encode("utf-8")
        return hmac.new(PLATFORM_HANDOFF_SECRET, message, hashlib.sha256).hexdigest()

    @staticmethod
    def verify_token(token_hash: str, from_agent: str, to_agent: str, workflow_id: str, stage: str, gate_id: str) -> bool:
        """Verifies that a HandoffToken was legitimately generated by the preceding gate."""
        expected = HandoffValidator.generate_token(from_agent, to_agent, workflow_id, stage, gate_id)
        return hmac.compare_digest(token_hash, expected)

    @classmethod
    def validate_handoff_payload(cls, payload: Dict[str, Any], schema_path: Optional[Path] = None) -> Tuple[bool, List[str]]:
        """
        Validates payload against the standard handoff schema specification.
        Checks structure, required fields, date formats, and hash regex.
        """
        errors = []
        required_fields = ["handoff_id", "from_agent", "to_agent", "workflow_id", "stage", "payload_artifact", "token_hash", "timestamp"]
        for rf in required_fields:
            if rf not in payload:
                errors.append(f"Missing required field: '{rf}'")

        if "handoff_id" in payload:
            if not isinstance(payload["handoff_id"], str) or not re.match(r"^HO_[A-Za-z0-9_\-]+$", payload["handoff_id"]):
                errors.append(f"Invalid handoff_id format: '{payload.get('handoff_id')}'. Must match ^HO_[A-Za-z0-9_-]+$")

        if "token_hash" in payload:
            if not isinstance(payload["token_hash"], str) or not re.match(r"^[a-f0-9]{64}$", payload["token_hash"]):
                errors.append(f"Invalid token_hash format: '{payload.get('token_hash')}'. Must be 64-char lowercase hex.")

        if "timestamp" in payload:
            try:
                datetime.fromisoformat(payload["timestamp"].replace("Z", "+00:00"))
            except Exception as e:
                errors.append(f"Invalid timestamp ISO format: '{payload.get('timestamp')}': {str(e)}")

        # Check for unapproved extra top-level fields (additionalProperties: false)
        allowed = set(required_fields + ["metadata"])
        extras = set(payload.keys()) - allowed
        if extras:
            errors.append(f"Disallowed top-level payload fields: {list(extras)}")

        return (len(errors) == 0, errors)

    @classmethod
    def verify_route_authorization(cls, from_agent: str, to_agent: str, workflow_id: str) -> Tuple[bool, Optional[str]]:
        """
        Checks if the DAG allows `from_agent` to hand off directly to `to_agent` in `workflow_id`.
        Returns (is_authorized, required_gate_id).
        """
        wf_routes = AUTHORIZED_HANDOFF_ROUTES.get(workflow_id)
        if not wf_routes:
            # Allow custom workflows if from_agent != to_agent
            if from_agent and to_agent and from_agent != to_agent:
                return (True, "gate_custom_workflow_verification")
            return (False, None)

        gate_id = wf_routes.get((from_agent, to_agent))
        if gate_id:
            return (True, gate_id)
        return (False, None)

    @classmethod
    def process_handover(cls, payload: Dict[str, Any]) -> Dict[str, Any]:
        """
        End-to-end handover gatekeeper checking payload schema, route authorization, and token integrity.
        """
        # 1. Payload validation
        valid_schema, schema_errors = cls.validate_handoff_payload(payload)
        if not valid_schema:
            return {
                "status": "REJECTED_SCHEMA_DRIFT",
                "is_authorized": False,
                "errors": schema_errors,
                "timestamp": datetime.now(timezone.utc).isoformat()
            }

        # 2. Route authorization check
        from_agent = payload["from_agent"]
        to_agent = payload["to_agent"]
        workflow_id = payload["workflow_id"]
        stage = payload["stage"]
        token_hash = payload["token_hash"]

        is_auth, gate_id = cls.verify_route_authorization(from_agent, to_agent, workflow_id)
        if not is_auth:
            return {
                "status": "REJECTED_UNAUTHORIZED_HANDOVER",
                "is_authorized": False,
                "errors": [f"Direct handoff from '{from_agent}' to '{to_agent}' is forbidden in workflow '{workflow_id}'."],
                "timestamp": datetime.now(timezone.utc).isoformat()
            }

        # 3. Cryptographic token check
        valid_token = cls.verify_token(token_hash, from_agent, to_agent, workflow_id, stage, gate_id or "gate_generic")
        if not valid_token:
            return {
                "status": "REJECTED_FORGED_HANDOFF_TOKEN",
                "is_authorized": False,
                "errors": [f"HandoffToken '{token_hash[:12]}...' is forged or does not match gate '{gate_id}'."],
                "timestamp": datetime.now(timezone.utc).isoformat()
            }

        return {
            "status": "AUTHORIZED_HANDOFF_CONFIRMED",
            "is_authorized": True,
            "handoff_id": payload["handoff_id"],
            "from_agent": from_agent,
            "to_agent": to_agent,
            "workflow_id": workflow_id,
            "gate_id": gate_id,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "errors": []
        }
